export class DeliveryRequest {
    challanAttachId: number;
    challanDate: string;
    challanNo: string;
    driverName: string;
    driverPhone: string;
    eWayBillDate: string;
    ewayBillAttachId: number;
    ewayBillDate: string;
    ewayBillNo: string;
    invoiceAttachId: number;
    invoiceNo: string;
    lorryReceiptAttachId: number;
    lorryReceiptNo: string;
    materialTestAttachId: number;
    orderId: number;
    orderItemList: OrderItems[];
    transportDate: string;
    transportModeCd: string;
    transporterName: string;
    vehicleNo: string;
}

export class OrderItems {
    deliveryQty: number;
    poItemId: number;
}

export interface DocumentModel {
    accessType: string;
    bucketFilePath: string;
    cleanFileName: string;
    fileDownloadUri: string;
    filesize: number;
    id: number;
    localFilePath: string;
    mimeType: string;
    orginalFileName: string;
    responses?: null[];
    servingUrl: string;
    signedUrl: string;

    pid?: number;
}

// Generated by https://quicktype.io

export interface InitDeliverySummary {
    challanAttachId: string | number;
    challanDate: string | number;
    challanDateRaw: string | number;
    challanNo: string;
    driverName: string;
    driverPhone: string;
    ewayBillAttachId: number;
    ewayBillDate: string | number;
    ewayBillDateRaw: string | number;
    ewayBillNo: string;
    id: number;
    invoice: string | number;
    invoiceAmount: number;
    invoiceAttachId: number;
    invoiceDt: string | number;
    invoiceDtRaw: string | number;
    items: InitDeliverySummaryItem[];
    lorryReceiptAttachId: string | number;
    lorryReceiptNo: string;
    materialTestAttachId: string | number;
    materialTestDt: string | number;
    materialTestDtRaw: string | number;
    materialTestNo: string | number;
    orderId: number;
    orderNo: string | number;
    status: string | number;
    statusCd: string | number;
    totalAmountExludingTax: number;
    totalGst: number;
    transportDt: string | number;
    transportDtRaw: string | number;
    transportModeCd: string;
    transportModeName: string | number;
    transporterName: string;
    vehicleNo: string;
}

export interface InitDeliverySummaryItem {
    acceptDt: string;
    acceptDtRaw: string;
    acceptQty: number;
    deliverQty: number;
    deliveryInvoiceId: number;
    gstRate: number;
    id: number;
    imageUrl: string;
    invoiceAmount: number;
    itemId: number;
    itemQty: number;
    name: string;
    rejectQty: number;
    sellerPrice: number;
    seqNo: number;
    skuSlugUrl: string;
    totalAmountExludingTax: number;
    totalGst: number;
    unit: string;
}
