import { AddressModel } from './address';
import { FormGroup, FormArray } from '@angular/forms';
import { DocumentModel } from './delivery-request';

export interface RfqItem {

    freightTerm: string;
    freightTermCd: string;
    items: RfqSku[];
    paymentTerm: string;
    paymentTermCd: string;
    rfq: RfqDetails;
    validEndDt: string;


}



export interface RfqDetails {
    documents: any[];
    expireDt: string;
    expired: boolean;
    id: number;
    note: string;
    opsAttachId: number;
    paymentTerm: string;
    paymentTermId: number;
    pid: number;
    status: string;
    statusCd: string;
    createDt: string;
    sellerstoreYn?: string;
    closeYn?: string;
    closeRemark?: string;
    buyerPhone?: string;
    buyerEmail?: string;
}

export interface RfqSku {
    note: string;
    sellerRfqItem: RFQItemSkuDetails;
    warehousePrice: WareHousePrice;

    selectedAddress?: AddressModel;
    form?: FormGroup;

    expand?: boolean;
}

export interface RFQItemSkuDetails {
    brandIconImageUrl: string;
    buyerRfqItemBrandId: number;
    buyerRfqItemId: number;
    deliveryAddress: string;
    deliveryLocation: string;
    deliveryLocationCd: string;
    displayName: string;
    documents: DocumentModel[];
    id: number;
    imageUrl: string;
    maxQty: number;
    minPrice: number;
    minQty: number;
    note: string;
    pid: number;
    quotePrice: number;
    requestQty: number;
    requiredEndDt: string;
    requiredStartDt: string;
    rmcDesignMix: any;
    sellerRfqId: number;
    skuId: number;
    skuName: string;
    skuSlugUrl: string;
    specYn: string;
    specs: SkuSpecs[];
    status: string;
    statusCd: string;
    unit: string;
}


export interface SkuSpecs {
    id: number;
    maxQty: number;
    minQty: number;
    pid: number;
    price: number;
    quotePrice?: number;
    requestQty: number;
    sellerRfqItemId: number;
    skuId: number;
    skuName: string;
    specCd: string;
    specId: number;
    specName: string;
}


// Generated by https://quicktype.io

export interface WareHousePrice {
    id: number;
    warehousePriceList: WarehousePriceList[];
    warehouseAddress: WarehouseAddress;
    specs: any[];
    documents: any[];
}

export interface WarehouseAddress {
    addressId: number;
    addressLine1: string;
    addressLine2: string;
    name: string;
    phoneNo: string;
    pincode: string;
    defaultAddress: boolean;
    city: City;
    state: State;
    addressCategory: string;
    deliveryRange: number;
    htmlData: string;
}

export interface City {
    id: number;
    name: string;
    code: string;
    stateCode: string;
    stateId: number;
}

export interface State {
    id: number;
    name: string;
    code: string;
    countryId: number;
}

export interface WarehousePriceList {
    minQty: number;
    maxQty: number;
    price: number;
    samePriceAllWarehouse: boolean;
    warehouseId: number;
    note: string;
    sellerRfqItemId: number;
    specName: null;
    specRelId: null;
    validEndDt: string;
    paymentTermCd: string;
    paymentTerm: string;
    attachId: null;
    freightTermCd: string;
    freightTerm: string;
    requestQty: number;
}
